spring.application.name=simple
MaxAge = 10800
MYSQL_URL = jdbc:mysql://root:hfjFhhABiOBIRgLTGKZbLlegJnXMvaEu@gondola.proxy.rlwy.net:53447/railway
MYSQL_USERNAME = root
MYSQL_PASSWORD = hfjFhhABiOBIRgLTGKZbLlegJnXMvaEu

#MYSQL_URL = jdbc:mysql://localhost:3306/simple
#MYSQL_USERNAME = root
#MYSQL_PASSWORD = root